/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,scss}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'gh-bg-primary':     '#0d1117',
        'gh-bg-secondary':   '#161b22',
        'gh-bg-tertiary':    '#21262d',
        'gh-bg-overlay':     '#2d333b',
        'gh-border':         '#30363d',
        'gh-border-muted':   '#21262d',
        'gh-text-primary':   '#e6edf3',
        'gh-text-secondary': '#8b949e',
        'gh-text-muted':     '#6e7681',
        'gh-blue':           '#418FF1',
        'gh-blue-light':     '#388bfd',
        'gh-blue-bg':        '#1c2d3f',
        'gh-blue-border':    '#388bfd33',
        'gh-blue-text':      '#418FF1',
        'gh-green':          '#238636',
        'gh-green-bg':       '#1b2b1f',
        'gh-green-border':   '#2ea04380',
        'gh-green-text':     '#3fb950',
        'gh-red':            '#da3633',
        'gh-red-bg':         '#2d1a1a',
        'gh-red-border':     '#f8514940',
        'gh-red-text':       '#f85149',
        'gh-yellow':         '#bb8009',
        'gh-yellow-bg':      '#2d2007',
        'gh-yellow-border':  '#9e6a0340',
        'gh-yellow-text':    '#d29922',
        'gh-purple':         '#8957e5',
        'gh-purple-bg':      '#1e1229',
        'gh-purple-border':  '#8957e540',
        'gh-purple-text':    '#bc8cff',

        // ── Eksik olan kısım ──
        'gh-orange':         '#bd561d',
        'gh-orange-bg':      '#271d0e',
        'gh-orange-border':  '#db6d2840',
        'gh-orange-text':    '#db6d28',
        'gh-pink':           '#db61a2',
        'gh-pink-bg':        '#271221',
        'gh-pink-border':    '#db61a240',
        'gh-pink-text':      '#db61a2',

        'gh-light-bg-primary':    '#ffffff',
        'gh-light-bg-secondary':  '#f6f8fa',
        'gh-light-bg-tertiary':   '#eaeef2',
        'gh-light-border':        '#d0d7de',
        'gh-light-text-primary':  '#1f2328',
        'gh-light-text-secondary':'#656d76',
        'gh-light-text-muted':    '#8c959f',
        'gh-light-blue':          '#0969da',
        'gh-light-blue-hover':    '#0860ca',
        'gh-light-blue-bg':       '#ddf4ff',
        'gh-light-blue-border':   '#54aeff66',
        'gh-light-blue-text':     '#0550ae',
        'gh-light-green':         '#1a7f37',
        'gh-light-green-bg':      '#dafbe1',
        'gh-light-green-border':  '#aceebb',
        'gh-light-green-text':    '#116329',
        'gh-light-red':           '#d1242f',
        'gh-light-red-bg':        '#ffebe9',
        'gh-light-red-border':    '#ffcecb',
        'gh-light-red-text':      '#82071e',
        'gh-light-yellow':        '#9a6700',
        'gh-light-yellow-bg':     '#fff8c5',
        'gh-light-yellow-border': '#eac54f',
        'gh-light-yellow-text':   '#7d4e00',
        'gh-light-purple':        '#8250df',
        'gh-light-purple-bg':     '#fbefff',
        'gh-light-purple-border': '#d2a8ff',
        'gh-light-purple-text':   '#6639ba',

        // ── Eksik olan kısım ──
        'gh-light-orange':        '#bc4c00',
        'gh-light-orange-bg':     '#fff1e5',
        'gh-light-orange-border': '#ffc680',
        'gh-light-orange-text':   '#953800',
        'gh-light-pink':          '#bf3989',
        'gh-light-pink-bg':       '#ffeff7',
        'gh-light-pink-border':   '#ff80c8',
        'gh-light-pink-text':     '#99286e',
      },
    },
  },
  plugins: [],
}