import { Modal, Button, Card, Flex, Tag, Typography, Avatar } from 'antd'
import { FileOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import '../index.scss'

const { Text } = Typography

const SEVERITY_CLASS: Record<string, string> = {
    high: 'severity--high',
    medium: 'severity--medium',
    low: 'severity--low',
}

interface Props {
    open: boolean
    onClose: () => void
    result: any
}

const PRReportModal = ({ open, onClose, result }: Props) => {
    const { t } = useTranslation()

    if (!result) return null

    const handleDownload = () => {
        const lines: string[] = []

        lines.push(`# PR Review Report — ${result.title}`)
        lines.push(
            `\n**PR:** ${result.number} | **Author:** ${result.author} | **Risk Score:** ${result.riskScore}/100`
        )
        lines.push(`\n## Summary\n${result.summary}`)
        lines.push(`\n## Stats`)
        lines.push(`- ${t('prReview.changedFiles')}: ${result.changedFiles}`)
        lines.push(`- ${t('prReview.criticalIssues')}: ${result.criticalIssues}`)
        lines.push(`- ${t('prReview.issuesCount', { count: result.issues.length })}`)

        if (result.issues.length > 0) {
            lines.push(`\n## Issues`)
            result.issues.forEach((issue: any, i: number) => {
                lines.push(
                    `\n### ${i + 1}. ${issue.title} \`${issue.severity.toUpperCase()}\``
                )
                lines.push(`**File:** \`${issue.file}\``)
                lines.push(`\n${issue.description}`)
                if (issue.suggestion) {
                    lines.push(`\n💡 ${issue.suggestion}`)
                }
            })
        }

        if (result.files.length > 0) {
            lines.push(`\n## Changed Files`)
            result.files.forEach((file: any) => {
                lines.push(
                    `- \`${file.path}\` — ${file.changes} — ${t(`prReview.risk${file.risk.charAt(0).toUpperCase() + file.risk.slice(1)}`)}`
                )
            })
        }

        lines.push(`\n---\n*Generated by DevCrew PR Review Agent*`)

        const md = lines.join('\n')
        const blob = new Blob([md], { type: 'text/markdown' })
        const url = URL.createObjectURL(blob)

        const a = document.createElement('a')
        a.href = url
        a.download = `pr-review-${result.number}.md`
        a.click()

        URL.revokeObjectURL(url)
    }

    return (
        <Modal
            open={open}
            onCancel={onClose}
            title={`${t('prReview.title')} — ${result.number}`}
            width={720}
            footer={
                <Flex gap={8} justify="flex-end">
                    <Button
                        className="pr-report-modal__download-btn"
                        onClick={handleDownload}
                    >
                        {t('prReview.downloadPatch')?.replace('.patch', '.md')}
                    </Button>
                </Flex>
            }
        >
            <Flex vertical gap={16} className="pr-report-modal">
                <Flex vertical gap={6}>
                    <Text className="pr-review__section-label">
                        {t('prReview.responseLabel')}
                    </Text>
                    <Text className="pr-report-modal__summary">
                        {result?.summary}
                    </Text>
                </Flex>

                <Flex gap={10} className="pr-report-modal__stats">
                    <Card className="pr-review__score-card pr-review__score-card--danger pr-report-modal__stat-card">
                        <Text type="secondary" className="pr-review__score-label">
                            {t('prReview.riskScore')}
                        </Text>
                        <Text className="pr-review__score-value pr-review__score-value--danger">
                            {result?.riskScore}
                        </Text>
                    </Card>

                    <Card className="pr-review__score-card pr-review__score-card--neutral pr-report-modal__stat-card">
                        <Text type="secondary" className="pr-review__score-label">
                            {t('prReview.changedFiles')}
                        </Text>
                        <Text className="pr-review__score-value">
                            {result?.changedFiles}
                        </Text>
                    </Card>

                    <Card className="pr-review__score-card pr-review__score-card--warning pr-report-modal__stat-card">
                        <Text type="secondary" className="pr-review__score-label">
                            {t('prReview.criticalIssues')}
                        </Text>
                        <Text className="pr-review__score-value pr-review__score-value--warning">
                            {result?.criticalIssues}
                        </Text>
                    </Card>
                </Flex>

                {result?.issues?.length > 0 && (
                    <Flex vertical gap={6}>
                        <Text className="pr-review__section-label">
                            {t('prReview.filesLabel')}
                        </Text>

                        <Flex vertical gap={8}>
                            {result?.issues?.map((issue: any, index: number) => (
                                <div
                                    key={index}
                                    className={`pr-review__issue-item ${SEVERITY_CLASS[issue?.severity] || ''
                                        }`}
                                >
                                    <Text strong className="pr-review__issue-title">
                                        {issue?.title}
                                    </Text>

                                    <Text
                                        type="secondary"
                                        className="pr-review__issue-desc"
                                    >
                                        {issue?.description}
                                    </Text>

                                    {issue?.suggestion && (
                                        <Text className="pr-review__issue-suggestion">
                                            💡 {issue?.suggestion}
                                        </Text>
                                    )}

                                    <Text className="pr-review__issue-file">
                                        {issue?.file}
                                    </Text>
                                </div>
                            ))}
                        </Flex>
                    </Flex>
                )}

                {result?.files?.length > 0 && (
                    <Flex vertical gap={6}>
                        <Text className="pr-review__section-label">
                            {t('prReview.filesLabel')}
                        </Text>

                        <Flex vertical gap={6}>
                            {result?.files?.map((file: any) => (
                                <Flex
                                    key={file.name}
                                    align="center"
                                    gap={10}
                                    className="pr-review__file-item"
                                >
                                    <Avatar
                                        icon={<FileOutlined />}
                                        className="pr-review__file-avatar"
                                        size={32}
                                    />

                                    <Flex
                                        vertical
                                        gap={2}
                                        className="pr-review__file-info"
                                    >
                                        <Text code className="pr-review__file-name">
                                            {file?.name}
                                        </Text>

                                        <Text
                                            type="secondary"
                                            className="pr-review__file-meta"
                                        >
                                            {file?.path} · {file?.changes}
                                        </Text>
                                    </Flex>

                                    <Tag
                                        className={`pr-review__risk-tag pr-review__risk-tag--${file?.risk}`}
                                    >
                                        {t(
                                            `prReview.risk${file?.risk.charAt(0).toUpperCase() +
                                            file?.risk.slice(1)
                                            }`
                                        )}
                                    </Tag>
                                </Flex>
                            ))}
                        </Flex>
                    </Flex>
                )}
            </Flex>
        </Modal>
    )
}

export default PRReportModal